services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node
    working_dir: /workspace
    container_name: devcontainer
    entrypoint: ""
    command: [/bin/bash, -c, "cd /root/.devcontainer && ./init.sh && tail -f /dev/null"] 
    stdin_open: true
    tty: true
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - /run/host-services/ssh-auth.sock:/ssh-agent:ro
      - ./mount:/root/.devcontainer:ro
      - ~/.config/nvim:/root/.config/nvim
      - ../Projects:/workspace
